version: '3.7'
services:
  mysql-n1:
    image: mysql:8.0.30
    hostname: mysql-n1
    ports:
    - 3306:3306
    user: root
    restart: always
    environment:
    - MYSQL_ROOT_HOST=%
    - MYSQL_ROOT_PASSWORD=isoftstone
    - TZ=Asia/Shanghai
    volumes:
    - ./data/mysql-n1/db:/var/lib/mysql
    - ./data/mysql-n1/logs:/var/log/mysql/
    - ./init.d/master:/docker-entrypoint-initdb.d/:ro
    - ./config:/etc/mysql/conf.d/:rw
    command:
    - "--server-id=1"
    - "--default-authentication-plugin=mysql_native_password"
    - "--character-set-server=utf8mb4"
    - "--max_connections=16384"
    - "--collation-server=utf8mb4_general_ci"
    - "--explicit_defaults_for_timestamp=true"
    - "--lower_case_table_names=1"
    - "--binlog-ignore-db=mysql"
    - "--binlog_format=row"
    - "--log-bin=mysql-bin"
    - "--sync_binlog=1"
    - "--expire_logs_days=7"
    - "--slave_skip_errors=1062"
    - "--sql_mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"
    networks:
    - edge-gateway-work
    deploy:
      placement:
        constraints:
        - node.hostname == dockerMaster
        - node.role == manager
  mysql-n2:
    image: mysql:8.0.30
    hostname: mysql-n2
    user: root
    restart: always
    environment:
    - MYSQL_ROOT_HOST=%
    - MYSQL_ROOT_PASSWORD=isoftstone
    - TZ=Asia/Shanghai
    volumes:
    - ./data/mysql-n2/db:/var/lib/mysql
    - ./data/mysql-n2/logs:/var/log/mysql/
    - ./init.d/slave/:/docker-entrypoint-initdb.d/:ro
    - ./config:/etc/mysql/conf.d/:rw
    command:
    - "--server-id=2"
    - "--default-authentication-plugin=mysql_native_password"
    - "--character-set-server=utf8mb4"
    - "--max_connections=16384"
    - "--collation-server=utf8mb4_general_ci"
    - "--explicit_defaults_for_timestamp=true"
    - "--lower_case_table_names=1"
    - "--binlog-ignore-db=mysql"
    - "--binlog_format=row"
    - "--log-bin=mysql-bin"
    - "--sync_binlog=1"
    - "--expire_logs_days=7"
    - "--slave_skip_errors=1062"
    - "--sql_mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"
    depends_on:
    - mysql-n1
    networks:
    - edge-gateway-work
    deploy:
      placement:
        constraints:
        - node.hostname == dockerNode1
        - node.role == worker
  mysql-n3:
    image: mysql:8.0.30
    hostname: mysql-n3
    user: root
    restart: always
    environment:
    - MYSQL_ROOT_HOST=%
    - MYSQL_ROOT_PASSWORD=isoftstone
    - TZ=Asia/Shanghai
    volumes:
    - ./data/mysql-n3/db:/var/lib/mysql
    - ./data/mysql-n3/logs:/var/log/mysql/
    - ./init.d/slave:/docker-entrypoint-initdb.d/:ro
    - ./config:/etc/mysql/conf.d/:rw
    command:
    - "--server-id=3"
    - "--default-authentication-plugin=mysql_native_password"
    - "--character-set-server=utf8mb4"
    - "--max_connections=16384"
    - "--collation-server=utf8mb4_general_ci"
    - "--explicit_defaults_for_timestamp=true"
    - "--lower_case_table_names=1"
    - "--binlog-ignore-db=mysql"
    - "--binlog_format=row"
    - "--log-bin=mysql-bin"
    - "--sync_binlog=1"
    - "--expire_logs_days=7"
    - "--slave_skip_errors=1062"
    - "--sql_mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"
    depends_on:
    - mysql-n1
    - mysql-n2
    networks:
    - edge-gateway-work
    deploy:
      placement:
        constraints:
        - node.hostname == dockerNode2
        - node.role == worker

networks:
  edge-gateway-work:
    driver: overlay
    external: true


